### ISSUE TITLE
No bindings file found 

### ISSUE THREAD

**Issue by ianmin2** [aksalj/pesajs#14]
> Hello, I know that this is most probably the wrong place to post this since it is a dependency issue but it seems like my best option right now.
I

I am running on Ubuntu 16.04 64bit with nodejs 7.7.1 and when I try to run the included example file in your package, i get the following error.

```
> `/usr/lib/node_modules/bindings/bindings.js:91
>   throw err
>   ^
> 
> Error: Could not locate the bindings file. Tried:
>  → /usr/lib/node_modules/node-expat/build/node_expat.node
>  → /usr/lib/node_modules/node-expat/build/Debug/node_expat.node
>  → /usr/lib/node_modules/node-expat/build/Release/node_expat.node
>  → /usr/lib/node_modules/node-expat/out/Debug/node_expat.node
>  → /usr/lib/node_modules/node-expat/Debug/node_expat.node
>  → /usr/lib/node_modules/node-expat/out/Release/node_expat.node
>  → /usr/lib/node_modules/node-expat/Release/node_expat.node
>  → /usr/lib/node_modules/node-expat/build/default/node_expat.node
>  → /usr/lib/node_modules/node-expat/compiled/7.7.1/linux/x64/node_expat.node
>     at bindings (/usr/lib/node_modules/bindings/bindings.js:88:9)
>     at Object.<anonymous> (/usr/lib/node_modules/node-expat/lib/node-expat.js:4:32)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/lib/node_modules/xml2json/lib/xml2json.js:1:75)
> `
```

_I have tried to re-install node-gyp and node_expat  both natively and using npm as well as **node-gyp rebuild** in the **/usr/lib/node_modules/node-expat/**  directory all to no avail._

_In a bid to see if it was a configuration error on my machine, I spawned a fresh ubuntu 16.04 64 bit VPS installed nodejs 7.7.1 and tried to run the same only to get the same error _

I will greatly appreciate your assistance

**Comment by NateNjuguna** [comment]
This module may not have support for node 7.x buglabs/node-xml2json#130
